//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public int RequestType { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> MainActId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public Nullable<int> DeliveriesId { get; set; }
        public Nullable<int> TechSpecsId { get; set; }
        public Nullable<int> RepairId { get; set; }
        public Nullable<int> PurchaseRequestId { get; set; }
        public Nullable<int> CustomerActionSheetId { get; set; }
        public Nullable<int> PGNRequestId { get; set; }
        public string CreatedById { get; set; }
        public Nullable<int> ActionsDropdowns_Id { get; set; }
        public Nullable<int> ActionsDropdowns_Id1 { get; set; }
        public Nullable<int> ActionsDropdowns_Id2 { get; set; }
        public Nullable<int> ActionsDropdowns_Id3 { get; set; }
        public Nullable<int> MOAccountUserId { get; set; }
    
        public virtual ActionsDropdown ActionsDropdown { get; set; }
        public virtual ActionsDropdown ActionsDropdown1 { get; set; }
        public virtual ActionsDropdown ActionsDropdown2 { get; set; }
        public virtual ActionsDropdown ActionsDropdown3 { get; set; }
        public virtual ActionsDropdown ActionsDropdown4 { get; set; }
        public virtual ActionsDropdown ActionsDropdown5 { get; set; }
        public virtual ActionsDropdown ActionsDropdown6 { get; set; }
        public virtual ActionsDropdown ActionsDropdown7 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CustomerActionSheet CustomerActionSheet { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual MOAccountUser MOAccountUser { get; set; }
        public virtual PGNRequest PGNRequest { get; set; }
        public virtual PurchaseRequest PurchaseRequest { get; set; }
        public virtual Repair Repair { get; set; }
        public virtual TechSpec TechSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
