//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparisonReportSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComparisonReportSpec()
        {
            this.ComparisonReportSpecsDetails = new HashSet<ComparisonReportSpecsDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Unit { get; set; }
        public string Type { get; set; }
        public string PR { get; set; }
        public string Quotation { get; set; }
        public string PO { get; set; }
        public string ActualDelivery { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDiscrepancy { get; set; }
        public Nullable<int> ComparisonReportId { get; set; }
    
        public virtual ComparisonReport ComparisonReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComparisonReportSpecsDetail> ComparisonReportSpecsDetails { get; set; }
    }
}
