//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparisonReportSpecsDetail
    {
        public int Id { get; set; }
        public int ItemOrder { get; set; }
        public string Type { get; set; }
        public string PR { get; set; }
        public string Quotation { get; set; }
        public string PO { get; set; }
        public string ActualDelivery { get; set; }
        public Nullable<bool> IsDiscrepancy { get; set; }
        public Nullable<int> ComparisonReportSpecsId { get; set; }
    
        public virtual ComparisonReportSpec ComparisonReportSpec { get; set; }
    }
}
