//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.Actions = new HashSet<Action>();
            this.ComparisonReports = new HashSet<ComparisonReport>();
            this.DeliveriesSpecs = new HashSet<DeliveriesSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public long RequestedById { get; set; }
        public long ReqByChiefId { get; set; }
        public long DeliveredById { get; set; }
        public int Gender { get; set; }
        public string ContactNo { get; set; }
        public string PONo { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComparisonReport> ComparisonReports { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TicketRequest TicketRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesSpec> DeliveriesSpecs { get; set; }
    }
}
