//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveriesSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveriesSpec()
        {
            this.DeliveriesSpecsDetails = new HashSet<DeliveriesSpecsDetail>();
        }
    
        public int Id { get; set; }
        public int ItemNo { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int Quantity { get; set; }
        public int Unit { get; set; }
        public long UnitCost { get; set; }
        public long TotalCost { get; set; }
        public long ProposedBudget { get; set; }
        public string Purpose { get; set; }
        public bool IsActive { get; set; }
        public string SerialNo { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> DeliveriesId { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesSpecsDetail> DeliveriesSpecsDetails { get; set; }
    }
}
