//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOAccount()
        {
            this.MOAccountUsers = new HashSet<MOAccountUser>();
        }
    
        public int Id { get; set; }
        public string PrincipalName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedById { get; set; }
        public Nullable<int> OfficeId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PGNGroupOffice PGNGroupOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAccountUser> MOAccountUsers { get; set; }
    }
}
