//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionsDropdown> ActionsDropdowns { get; set; }
        public virtual DbSet<ActionTaken> ActionTakens { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<ComparisonReport> ComparisonReports { get; set; }
        public virtual DbSet<ComparisonReportSpec> ComparisonReportSpecs { get; set; }
        public virtual DbSet<ComparisonReportSpecsDetail> ComparisonReportSpecsDetails { get; set; }
        public virtual DbSet<CustomerActionSheet> CustomerActionSheets { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveriesSpec> DeliveriesSpecs { get; set; }
        public virtual DbSet<DeliveriesSpecsDetail> DeliveriesSpecsDetails { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentSpec> EquipmentSpecs { get; set; }
        public virtual DbSet<EquipmentSpecsDetail> EquipmentSpecsDetails { get; set; }
        public virtual DbSet<ITStaff> ITStaffs { get; set; }
        public virtual DbSet<MOAccount> MOAccounts { get; set; }
        public virtual DbSet<MOAccountUser> MOAccountUsers { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<PGNAccount> PGNAccounts { get; set; }
        public virtual DbSet<PGNDocument> PGNDocuments { get; set; }
        public virtual DbSet<PGNGroupOffice> PGNGroupOffices { get; set; }
        public virtual DbSet<PGNMacAddress> PGNMacAddresses { get; set; }
        public virtual DbSet<PGNNonEmployee> PGNNonEmployees { get; set; }
        public virtual DbSet<PGNRequest> PGNRequests { get; set; }
        public virtual DbSet<PPE> PPEs { get; set; }
        public virtual DbSet<PPEsSpec> PPEsSpecs { get; set; }
        public virtual DbSet<PPEsSpecsDetail> PPEsSpecsDetails { get; set; }
        public virtual DbSet<PRStandardPRSpec> PRStandardPRSpecs { get; set; }
        public virtual DbSet<PurchaseRequest> PurchaseRequests { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<RoleDesignation> RoleDesignations { get; set; }
        public virtual DbSet<StandardPRSpec> StandardPRSpecs { get; set; }
        public virtual DbSet<StandardPRSpecsDetail> StandardPRSpecsDetails { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TechSpec> TechSpecs { get; set; }
        public virtual DbSet<TechSpecsBasi> TechSpecsBasis { get; set; }
        public virtual DbSet<TechSpecsICTSpec> TechSpecsICTSpecs { get; set; }
        public virtual DbSet<TechSpecsICTSpecsDetail> TechSpecsICTSpecsDetails { get; set; }
        public virtual DbSet<TicketRequest> TicketRequests { get; set; }
        public virtual DbSet<TicketRequestStatu> TicketRequestStatus { get; set; }
    }
}
