//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PGNAccount()
        {
            this.PGNMacAddresses = new HashSet<PGNMacAddress>();
        }
    
        public int Id { get; set; }
        public Nullable<long> HRMISEmpId { get; set; }
        public string Username { get; set; }
        public int UserType { get; set; }
        public int Status { get; set; }
        public Nullable<int> SignInCount { get; set; }
        public int TrafficSpeed { get; set; }
        public int Designation { get; set; }
        public string Remarks { get; set; }
        public string Password { get; set; }
        public Nullable<int> PGNGroupOfficesId { get; set; }
        public Nullable<int> PGNNonEmployeeId { get; set; }
        public Nullable<int> PGNRequestId { get; set; }
    
        public virtual PGNGroupOffice PGNGroupOffice { get; set; }
        public virtual PGNNonEmployee PGNNonEmployee { get; set; }
        public virtual PGNRequest PGNRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PGNMacAddress> PGNMacAddresses { get; set; }
    }
}
