//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPE()
        {
            this.MOAccountUsers = new HashSet<MOAccountUser>();
            this.PPEsSpecs = new HashSet<PPEsSpec>();
            this.Repairs = new HashSet<Repair>();
        }
    
        public int Id { get; set; }
        public Nullable<long> IssuedToId { get; set; }
        public Nullable<long> ChiefId { get; set; }
        public Nullable<int> Gender { get; set; }
        public string ContactNo { get; set; }
        public string PropertyNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> AquisitionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public int Quantity { get; set; }
        public int Unit { get; set; }
        public Nullable<long> UnitValue { get; set; }
        public Nullable<long> TotalValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAccountUser> MOAccountUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPEsSpec> PPEsSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repairs { get; set; }
    }
}
