//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardPRSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StandardPRSpec()
        {
            this.PRStandardPRSpecs = new HashSet<PRStandardPRSpec>();
            this.StandardPRSpecsDetails = new HashSet<StandardPRSpecsDetail>();
        }
    
        public int Id { get; set; }
        public int ItemNo { get; set; }
        public int Quarter { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public int Unit { get; set; }
        public Nullable<long> UnitCost { get; set; }
        public int EquipmentSpecsId { get; set; }
    
        public virtual EquipmentSpec EquipmentSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRStandardPRSpec> PRStandardPRSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPRSpecsDetail> StandardPRSpecsDetails { get; set; }
    }
}
