//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecsICTSpecsDetail
    {
        public int Id { get; set; }
        public int ItemNo { get; set; }
        public string Specs { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int TechSpecsICTSpecsId { get; set; }
    
        public virtual TechSpecsICTSpec TechSpecsICTSpec { get; set; }
    }
}
