//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecsBasi
    {
        public int Id { get; set; }
        public double PriceRange { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
        public string URLBasis { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Available { get; set; }
        public int EquipmentSpecsId { get; set; }
    
        public virtual EquipmentSpec EquipmentSpec { get; set; }
    }
}
