//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecsICTSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechSpecsICTSpec()
        {
            this.TechSpecsICTSpecsDetails = new HashSet<TechSpecsICTSpecsDetail>();
        }
    
        public int Id { get; set; }
        public int ItemNo { get; set; }
        public int Quantity { get; set; }
        public int Unit { get; set; }
        public long UnitCost { get; set; }
        public long TotalCost { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public int TechSpecsId { get; set; }
        public int EquipmentSpecsId { get; set; }
        public int TechSpecsICTSpecsDetailsId { get; set; }
    
        public virtual EquipmentSpec EquipmentSpec { get; set; }
        public virtual TechSpec TechSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecsICTSpecsDetail> TechSpecsICTSpecsDetails { get; set; }
    }
}
