//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketRequest()
        {
            this.TicketRequestStatus = new HashSet<TicketRequestStatu>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int TicketStatus { get; set; }
        public int RequestType { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<bool> IsRepairTechSpecs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual ITStaff ITStaff { get; set; }
        public virtual Repair Repair { get; set; }
        public virtual TechSpec TechSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketRequestStatu> TicketRequestStatus { get; set; }
    }
}
