//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRequestStatu
    {
        public int Id { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateStatusChanged { get; set; }
        public string ChangedByUserId { get; set; }
        public int TicketRequestId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TicketRequest TicketRequest { get; set; }
    }
}
